# Generated by Django 2.2.12 on 2020-04-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='unit_price',
            new_name='unit',
        ),
    ]
